export const actionTypes = {
    INCREMENT: 'COUNTER/INCREMENT',
    DECREMENT: 'COUNTER/DECREMENT',
    CHANGENAME:'COUNTER/NAME-CHANGE',
    CHANGEA_AND_INNCREMENT:'COUNTER/CHANGEA_AND_INNCREMENT'
}